_wandb:
    value:
        cli_version: 0.19.5
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.12.3
            "5": 0.19.5
            "8":
                - 5
            "12": 0.19.5
            "13": linux-x86_64
architecture:
    value: minLSTM
batch_size:
    value: 64
dataset:
    value: tiny-shakespeare
dropout:
    value: 0.15
embedding_size:
    value: 768
epochs:
    value: 5
hidden_sizes:
    value:
        - 64
        - 128
        - 256
        - 512
        - 1024
learning_rate:
    value: 0.001
normalize:
    value: true
optimizer:
    value: adamw
sequence_length:
    value: 256
vocabulary_size:
    value: 50257
